cask "font-jetbrains-mono-nerd-font-latest" do
  version "2.242"
  sha256 "bf8a78e02df7e8a5a6ffa6d29cbb39773513bbd126ee46c8f5edb0f267d6a1e1"

  url "https://github.com/kidonng/homebrew-malt/releases/download/binaries/font-jetbrains-mono-nerd-font-#{version}.zip"
  name "JetBrainsMono Nerd Font (JetBrains Mono)"
  homepage "https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono"

  font "JetBrains Mono Bold Nerd Font Complete.ttf"
  font "JetBrains Mono Bold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono ExtraBold Nerd Font Complete.ttf"
  font "JetBrains Mono ExtraBold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono ExtraLight Nerd Font Complete.ttf"
  font "JetBrains Mono ExtraLight Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Light Nerd Font Complete.ttf"
  font "JetBrains Mono Light Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Medium Nerd Font Complete.ttf"
  font "JetBrains Mono Medium Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Regular Nerd Font Complete.ttf"
  font "JetBrains Mono Italic Nerd Font Complete.ttf"
  font "JetBrains Mono SemiBold Nerd Font Complete.ttf"
  font "JetBrains Mono SemiBold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Thin Nerd Font Complete.ttf"
  font "JetBrains Mono Thin Italic Nerd Font Complete.ttf"
end
